### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ffaggiani** [ggabarrin/apdu-parser#1]
`root@---:~/apdu-parser# python apdu_parser.py -i sample_files/default_log.txt -c`

`A6 : CHECK RESET AND APPLET SELECTION (x)
    00 A6 00 00 00
Traceback (most recent call last):
  File "apdu_parser.py", line 141, in <module>
    main()
  File "apdu_parser.py", line 115, in main
    result = parse_apdu_command(apdu_line, command_descriptions)
  File "apdu_parser.py", line 23, in parse_apdu_command
    p1 = command_bytes[2]
IndexError: list index out of range`

**Comment by ggabarrin** [comment]
El archivo de entrada del parser debe tener el formato XX XX XX y no XXXXXX (siendo XX los bytes en hexadecimal).
